# dam_enginev2.py
import os
import sys
from pathlib import Path
import pandas as pd
import pulp

def locate_latest_prediction_file(search_dir: Path) -> Path:
    """Finds the most recent prediction Excel file generated by the forecast module."""
    files = list(search_dir.glob("Greece_Market_Price_Forecasts_*.xlsx"))
    if not files:
        return None
    files.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    return files[0]

def optimize_single_day(
    df_day: pd.DataFrame,
    E_initial: float,
    duration: float = 2.0,
    Cs: float = 1.5,
    pc_max_input: float = 1.0,
    pd_max_input: float = 1.0,
    n_c_input: float = 0.95,
    n_d_input: float = 0.95,
):
    """
    Optimizes BESS operations for a single calendar day (H quarters).
    Preserves all original constraints and returns (df_day_schedule, df_day_financials, final_e).
    """
    first_col = df_day.columns[0]
    price_col = "Price_Prediction_EUR_MWh" if "Price_Prediction_EUR_MWh" in df_day.columns else "DAM_Price"

    timestamps = df_day[first_col].astype(str).tolist()
    market_prices = df_day[price_col].fillna(0.0).tolist()
    fcr_up_prices = df_day["FCR_Up_Price_EUR_MW"].tolist()
    fcr_dn_prices = df_day["FCR_Down_Price_EUR_MW"].tolist()
    afrr_up_prices = df_day["aFRR_Up_Price_EUR_MW"].tolist()
    afrr_dn_prices = df_day["aFRR_Down_Price_EUR_MW"].tolist()
    mfrr_up_prices = df_day["mFRR_Up_Price_EUR_MW"].tolist()
    mfrr_dn_prices = df_day["mFRR_Down_Price_EUR_MW"].tolist()

    H = len(market_prices)
    if H == 0:
        return None, None, E_initial

    # Technical Asset Parameters & Constants
    Pc_max = pc_max_input   
    Pd_max = pd_max_input   
    Emax = duration * ((Pc_max + Pd_max) / 2)   
    Emin = 0.05 * Emax          
    E_final_target = 0.5 * Emax

    Pc_dam_max = Pc_max - 0.1 * Pc_max
    Pd_dam_max = Pd_max - 0.1 * Pd_max

    P_reserve_dn_max = 0.1 * Pc_max
    P_reserve_up_max = 0.1 * Pd_max

    N_c = n_c_input         
    Nd = n_d_input         
    dt = 0.25  # 15-minute resolution

    # Activation Multipliers & Flags
    Afcr_dn, Afcr_up = 0.05, 0.05
    Aafrr_dn, Aafrr_up = 0.85, 0.10
    Amfrr_dn, Amfrr_up = 0.50, 0.50

    FCR_Activation = 1
    aFRR_Activation = 1
    mFRR_Activation = 1

    max_quarters_cap_up = 12
    max_quarters_cap_dn = 12

    model = pulp.LpProblem("BESS_Daily_Optimization", pulp.LpMaximize)

    # Decision Variables
    fcr_dn = pulp.LpVariable.dicts("fcr_dn", range(H), lowBound=0, upBound=Pc_max)
    fcr_up = pulp.LpVariable.dicts("fcr_up", range(H), lowBound=0, upBound=Pd_max)
    afrr_dn = pulp.LpVariable.dicts("afrr_dn", range(H), lowBound=0, upBound=Pc_max)
    afrr_up = pulp.LpVariable.dicts("afrr_up", range(H), lowBound=0, upBound=Pd_max)
    mfrr_dn = pulp.LpVariable.dicts("mfrr_dn", range(H), lowBound=0, upBound=Pc_max)
    mfrr_up = pulp.LpVariable.dicts("mfrr_up", range(H), lowBound=0, upBound=Pd_max)
    
    e = pulp.LpVariable.dicts("e", range(H), lowBound=Emin, upBound=Emax)
    p_ch = pulp.LpVariable.dicts("p_ch", range(H), lowBound=0, upBound=Pc_max)
    p_dh = pulp.LpVariable.dicts("p_dh", range(H), lowBound=0, upBound=Pd_max)
    dam_ch = pulp.LpVariable.dicts("dam_ch", range(H), lowBound=0, upBound=Pc_dam_max)
    dam_dh = pulp.LpVariable.dicts("dam_dh", range(H), lowBound=0, upBound=Pd_dam_max)

    u_ch = pulp.LpVariable.dicts("u_ch", range(H), cat="Binary")
    u_dh = pulp.LpVariable.dicts("u_dh", range(H), cat="Binary")
    u_dam_ch = pulp.LpVariable.dicts("u_dam_ch", range(H), cat="Binary")
    u_dam_dh = pulp.LpVariable.dicts("u_dam_dh", range(H), cat="Binary")
    u_fcr_up = pulp.LpVariable.dicts("u_fcr_up", range(H), cat="Binary")
    u_fcr_dn = pulp.LpVariable.dicts("u_fcr_dn", range(H), cat="Binary")
    u_afrr_up = pulp.LpVariable.dicts("u_afrr_up", range(H), cat="Binary")
    u_afrr_dn = pulp.LpVariable.dicts("u_afrr_dn", range(H), cat="Binary")
    u_mfrr_up = pulp.LpVariable.dicts("u_mfrr_up", range(H), cat="Binary")
    u_mfrr_dn = pulp.LpVariable.dicts("u_mfrr_dn", range(H), cat="Binary")

    # Additional Binary Variables for Non-Simultaneous Reserve Activation
    u_cap_up = pulp.LpVariable.dicts("u_cap_up", range(H), cat="Binary")
    u_cap_dn = pulp.LpVariable.dicts("u_cap_dn", range(H), cat="Binary")

    # Objective Function
    model.setObjective(pulp.lpSum(
        market_prices[h] * (dam_dh[h] - dam_ch[h]) * dt +
        fcr_up_prices[h] * fcr_up[h] + fcr_dn_prices[h] * fcr_dn[h] +
        afrr_up_prices[h] * afrr_up[h] + afrr_dn_prices[h] * afrr_dn[h] +
        mfrr_up_prices[h] * mfrr_up[h] + mfrr_dn_prices[h] * mfrr_dn[h]
        for h in range(H)
    ))

    # 1. Energy Balance
    model.addConstraint(e[0] == E_initial + (N_c * p_ch[0] - (1 / Nd) * p_dh[0]) * dt)
    
    for h in range(H):
        model.addConstraint(
            p_ch[h] - p_dh[h] == dam_ch[h] - dam_dh[h] + 
            Afcr_dn*fcr_dn[h] - Afcr_up*fcr_up[h] + 
            Aafrr_dn*afrr_dn[h] - Aafrr_up*afrr_up[h] + 
            Amfrr_dn*mfrr_dn[h] - Amfrr_up*mfrr_up[h]
        )

    for h in range(1, H):
        model.addConstraint(e[h] == e[h - 1] + (N_c * p_ch[h] - (1 / Nd) * p_dh[h]) * dt)

    # 2. Binary & Capacity Constraints
    for h in range(H):
        model.addConstraint(p_ch[h] <= Pc_max * u_ch[h])
        model.addConstraint(p_dh[h] <= Pd_max * u_dh[h])
        model.addConstraint(dam_ch[h] <= Pc_dam_max * u_dam_ch[h])
        model.addConstraint(dam_dh[h] <= Pd_dam_max * u_dam_dh[h])
        
        model.addConstraint(fcr_up[h] <= Pd_max * u_fcr_up[h] * FCR_Activation)
        model.addConstraint(fcr_dn[h] <= Pc_max * u_fcr_dn[h] * FCR_Activation)
        model.addConstraint(afrr_up[h] <= Pd_max * u_afrr_up[h] * aFRR_Activation)
        model.addConstraint(afrr_dn[h] <= Pc_max * u_afrr_dn[h] * aFRR_Activation)
        model.addConstraint(mfrr_up[h] <= Pd_max * u_mfrr_up[h] * mFRR_Activation)
        model.addConstraint(mfrr_dn[h] <= Pc_max * u_mfrr_dn[h] * mFRR_Activation)
        
        model.addConstraint(fcr_up[h] + afrr_up[h] + mfrr_up[h] <= P_reserve_up_max)
        model.addConstraint(fcr_dn[h] + afrr_dn[h] + mfrr_dn[h] <= P_reserve_dn_max)

        model.addConstraint(u_ch[h] + u_dh[h] <= 1)
        model.addConstraint(u_dam_ch[h] + u_dam_dh[h] <= 1)
        
        model.addConstraint(
            dam_ch[h] + Afcr_dn*fcr_dn[h] - Afcr_up*fcr_up[h] + 
            Aafrr_dn*afrr_dn[h] - Aafrr_up*afrr_up[h] + 
            Amfrr_dn*mfrr_dn[h] - Amfrr_up*mfrr_up[h] <= Pc_max
        )
        model.addConstraint(
            dam_dh[h] + Afcr_up*fcr_up[h] - Afcr_dn*fcr_dn[h] + 
            Aafrr_up*afrr_up[h] - Aafrr_dn*afrr_dn[h] + 
            Amfrr_up*mfrr_up[h] - Amfrr_dn*mfrr_dn[h] <= Pd_max
        )

    # 3. Daily Cycle Limits
    model.addConstraint(pulp.lpSum(N_c * p_ch[h] * dt for h in range(H)) <= Cs * Emax)
    model.addConstraint(pulp.lpSum((1 / Nd) * p_dh[h] * dt for h in range(H)) <= Cs * Emax)

    # 4. Final Target SOE for this Day
    model.addConstraint(e[H - 1] >= 0.8 * E_final_target)
    model.addConstraint(e[H - 1] <= 1.2 * E_final_target)

    # 5. Reserve Limits
    model.addConstraint(pulp.lpSum(u_fcr_up[h] + u_afrr_up[h] + u_mfrr_up[h] for h in range(H)) <= max_quarters_cap_up)
    model.addConstraint(pulp.lpSum(u_fcr_dn[h] + u_afrr_dn[h] + u_mfrr_dn[h] for h in range(H)) <= max_quarters_cap_dn)
    '''
    # 6. non-simultaneous reserve activation constraints
    for h in range(H):
        # Mutual exclusion: Cannot provide Up and Down capacity in the same quarter
        model.addConstraint(u_cap_up[h] + u_cap_dn[h] <= 1)

        # Force individual reserve binaries to follow the directional state
        model.addConstraint(u_fcr_up[h] <= u_cap_up[h])
        model.addConstraint(u_afrr_up[h] <= u_cap_up[h])
        model.addConstraint(u_mfrr_up[h] <= u_cap_up[h])

        model.addConstraint(u_fcr_dn[h] <= u_cap_dn[h])
        model.addConstraint(u_afrr_dn[h] <= u_cap_dn[h])
        model.addConstraint(u_mfrr_dn[h] <= u_cap_dn[h])
   '''
    # Solve model
    model.solve(pulp.PULP_CBC_CMD(msg=False))
    solver_status = pulp.LpStatus[model.status]

    if solver_status == "Optimal":
        df_results = pd.DataFrame({
            "Delivery_Interval": timestamps,
            "DAM_Price_EUR_MWh": market_prices,
            "DAM_Charge_MW": [dam_ch[h].varValue for h in range(H)],
            "DAM_Discharge_MW": [dam_dh[h].varValue for h in range(H)],
            "Physical_Charge_MW": [p_ch[h].varValue for h in range(H)],
            "Physical_Discharge_MW": [p_dh[h].varValue for h in range(H)],
            "SOE_Capacity_MWh": [e[h].varValue for h in range(H)],
            "Total_Capacity_Up_MW": [fcr_up[h].varValue + afrr_up[h].varValue + mfrr_up[h].varValue for h in range(H)],
            "Total_Capacity_Dn_MW": [fcr_dn[h].varValue + afrr_dn[h].varValue + mfrr_dn[h].varValue for h in range(H)],
            "mFRR_Up_Capacity_MW": [mfrr_up[h].varValue for h in range(H)],
            "mFRR_Down_Capacity_MW": [mfrr_dn[h].varValue for h in range(H)],
            "FCR_Up_Capacity_MW": [fcr_up[h].varValue for h in range(H)],
            "FCR_Down_Capacity_MW": [fcr_dn[h].varValue for h in range(H)],
            "aFRR_Up_Capacity_MW": [afrr_up[h].varValue for h in range(H)],
            "aFRR_Down_Capacity_MW": [afrr_dn[h].varValue for h in range(H)]
        })

        dam_prof = sum(market_prices[h] * (dam_dh[h].varValue - dam_ch[h].varValue) * dt for h in range(H))
        fcr_up_prof = sum(fcr_up_prices[h] * fcr_up[h].varValue for h in range(H))
        fcr_dn_prof = sum(fcr_dn_prices[h] * fcr_dn[h].varValue for h in range(H))
        afrr_up_prof = sum(afrr_up_prices[h] * afrr_up[h].varValue for h in range(H))
        afrr_dn_prof = sum(afrr_dn_prices[h] * afrr_dn[h].varValue for h in range(H))
        mfrr_up_prof = sum(mfrr_up_prices[h] * mfrr_up[h].varValue for h in range(H))
        mfrr_dn_prof = sum(mfrr_dn_prices[h] * mfrr_dn[h].varValue for h in range(H))
        total_prof = pulp.value(model.objective)

        financials = {
            "DAM_Arbitrage_Profit": dam_prof,
            "FCR_Up_Profit": fcr_up_prof,
            "FCR_Dn_Profit": fcr_dn_prof,
            "aFRR_Up_Profit": afrr_up_prof,
            "aFRR_Dn_Profit": afrr_dn_prof,
            "mFRR_Up_Profit": mfrr_up_prof,
            "mFRR_Dn_Profit": mfrr_dn_prof,
            "Total_Daily_Profit": total_prof
        }

        ending_soe = e[H - 1].varValue
        return df_results, financials, ending_soe
    else:
        return None, None, E_initial


def run_bess_optimization(
    duration=2.0, 
    Cs=1.5, 
    pc_max_input=1.0, 
    pd_max_input=1.0, 
    n_c_input=0.95, 
    n_d_input=0.95,
    prediction_file_path=None,
    df_market_input=None
):
    """
    Executes sequential daily BESS optimizations, carrying over the ending SOE from day to day.
    """
    script_dir = Path(__file__).resolve().parent
    df_market = None

    # 1. Load Data Source (DataFrame or Excel)
    if df_market_input is not None and not df_market_input.empty:
        df_market = df_market_input.copy()
        source_label = "Historical Market Stream DataFrame"
    else:
        if prediction_file_path is None:
            prediction_file_path = locate_latest_prediction_file(script_dir)

        if prediction_file_path is None or not Path(prediction_file_path).exists():
            print("❌ Error: Forecast file 'Greece_Market_Price_Forecasts_*.xlsx' not found.", flush=True)
            return None, None

        source_label = Path(prediction_file_path).name
        try:
            df_dam = pd.read_excel(prediction_file_path, sheet_name="DAM_Energy_Forecast")
            df_res = pd.read_excel(prediction_file_path, sheet_name="Reserve_Capacity_Forecast")
            first_col_dam = df_dam.columns[0]
            first_col_res = df_res.columns[0]
            df_market = pd.merge(df_dam, df_res, left_on=first_col_dam, right_on=first_col_res)
        except Exception as err:
            print(f"❌ Error loading Excel workbook sheets: {err}", flush=True)
            return None, None

    print("\n" + "="*50, flush=True)
    print("🚀 INITIALIZING MULTI-MARKET BESS OPTIMIZATION ENGINE (DAILY ROLL)", flush=True)
    print(f"   Source: {source_label}", flush=True)
    print(f"   Parameters: Duration={duration}h, Cs={Cs} | Pc Max={pc_max_input}MW, Pd Max={pd_max_input}MW", flush=True)
    print("="*50, flush=True)

    first_col = df_market.columns[0]

    # Ensure required price vectors exist
    price_col = "Price_Prediction_EUR_MWh" if "Price_Prediction_EUR_MWh" in df_market.columns else "DAM_Price"
    if price_col not in df_market.columns:
        print(f"❌ Error: Could not identify DAM Price column in input dataset.", flush=True)
        return None, None

    reserve_cols = [
        "FCR_Up_Price_EUR_MW", "FCR_Down_Price_EUR_MW",
        "aFRR_Up_Price_EUR_MW", "aFRR_Down_Price_EUR_MW",
        "mFRR_Up_Price_EUR_MW", "mFRR_Down_Price_EUR_MW"
    ]
    for c in reserve_cols:
        if c not in df_market.columns:
            df_market[c] = 0.0
        else:
            df_market[c] = df_market[c].fillna(0.0)

    # Group market data chronologically by calendar date
    df_market["_calendar_date"] = pd.to_datetime(df_market[first_col]).dt.date
    unique_dates = df_market["_calendar_date"].unique()

    Emax = duration * ((pc_max_input + pd_max_input) / 2)
    current_soe = 0.5 * Emax  # Initial starting SOE for Day 1

    all_schedules = []
    tot_dam = tot_fcr_up = tot_fcr_dn = tot_afrr_up = tot_afrr_dn = tot_mfrr_up = tot_mfrr_dn = tot_prof = 0.0

    print(f"⏳ Solving {len(unique_dates)} distinct calendar days sequentially...", flush=True)

    for current_date in unique_dates:
        df_day = df_market[df_market["_calendar_date"] == current_date].drop(columns=["_calendar_date"])
        
        df_res_day, fin_day, next_soe = optimize_single_day(
            df_day=df_day,
            E_initial=current_soe,
            duration=duration,
            Cs=Cs,
            pc_max_input=pc_max_input,
            pd_max_input=pd_max_input,
            n_c_input=n_c_input,
            n_d_input=n_d_input
        )

        if df_res_day is None:
            print(f"❌ Solver Failure on date {current_date}", flush=True)
            return None, None

        all_schedules.append(df_res_day)
        current_soe = next_soe  # Carry ending energy into next day's E_initial

        tot_dam += fin_day["DAM_Arbitrage_Profit"]
        tot_fcr_up += fin_day["FCR_Up_Profit"]
        tot_fcr_dn += fin_day["FCR_Dn_Profit"]
        tot_afrr_up += fin_day["aFRR_Up_Profit"]
        tot_afrr_dn += fin_day["aFRR_Dn_Profit"]
        tot_mfrr_up += fin_day["mFRR_Up_Profit"]
        tot_mfrr_dn += fin_day["mFRR_Dn_Profit"]
        tot_prof += fin_day["Total_Daily_Profit"]

    df_results = pd.concat(all_schedules, ignore_index=True)
    df_summary = pd.DataFrame([{
        "Forecast_File": source_label,
        "DAM_Arbitrage_Profit": round(tot_dam, 2),
        "FCR_Up_Profit": round(tot_fcr_up, 2),
        "FCR_Dn_Profit": round(tot_fcr_dn, 2),
        "aFRR_Up_Profit": round(tot_afrr_up, 2),
        "aFRR_Dn_Profit": round(tot_afrr_dn, 2),
        "mFRR_Up_Profit": round(tot_mfrr_up, 2),
        "mFRR_Dn_Profit": round(tot_mfrr_dn, 2),
        "Total_Daily_Profit": round(tot_prof, 2)
    }])

    return df_results, df_summary


# =========================================================================
# STANDALONE LOCAL BACKTEST RUNNER (python dam_enginev2.py)
# =========================================================================
if __name__ == "__main__":
    from db_reader2 import fetch_henex_dam_db, fetch_ipto_reserve_prices_db

    # 1. Define Historical Date Range for Standalone Backtest
    start_date = "2026-01-01"
    end_date = "2026-07-31"

    print(f"\n⚡ Running Standalone Historical Backtest ({start_date} to {end_date})...")

    # 2. Fetch DAM and Reserve Prices from DuckDB
    df_dam = fetch_henex_dam_db(start_date, end_date)
    df_res_raw = fetch_ipto_reserve_prices_db(start_date, end_date, reserve_type="ALL")

    if df_dam.empty:
        print(f"❌ No DAM records found in database for range {start_date} to {end_date}.")
        sys.exit(1)

    if not df_res_raw.empty:
        df_res_raw = df_res_raw.rename(columns={"timestamp": "Delivery_Interval"})
        df_up = df_res_raw.pivot(index="Delivery_Interval", columns="reserve_type", values="price_up")
        df_down = df_res_raw.pivot(index="Delivery_Interval", columns="reserve_type", values="price_down")

        rename_up = {col: f"{col}_Up_Price_EUR_MW" for col in df_up.columns}
        rename_down = {col: f"{col}_Down_Price_EUR_MW" for col in df_down.columns}

        df_res_pivoted = pd.concat([
            df_up.rename(columns=rename_up),
            df_down.rename(columns=rename_down)
        ], axis=1).reset_index()

        df_hist_market = pd.merge(df_dam, df_res_pivoted, on="Delivery_Interval", how="left")
    else:
        df_hist_market = df_dam.copy()

    # 3. Solve Optimization
    df_schedule, df_financials = run_bess_optimization(
        duration=2.0,
        Cs=1.5,
        pc_max_input=1.0,
        pd_max_input=1.0,
        n_c_input=0.95,
        n_d_input=0.95,
        df_market_input=df_hist_market
    )

    if df_schedule is not None and df_financials is not None:
        first_dt = pd.to_datetime(df_schedule["Delivery_Interval"].iloc[0])
        last_dt = pd.to_datetime(df_schedule["Delivery_Interval"].iloc[-1])
        output_file = f"BESS_Optimized_Schedule_{first_dt.strftime('%d_%m')}_to_{last_dt.strftime('%d_%m')}.xlsx"

        # 4. Save to Excel with standard two-sheet structure
        with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
            df_schedule.to_excel(writer, sheet_name="BESS_Schedule", index=False)
            df_financials.to_excel(writer, sheet_name="Daily_Financial_Summary", index=False)

        # 5. Print Summary Table to Terminal
        print("\n" + "="*60)
        print(f"✅ HISTORICAL BACKTEST COMPLETED SUCCESSFULLY")
        print(f"📁 Output Saved: {output_file}")
        print("="*60)
        for col, val in df_financials.iloc[0].items():
            if "Profit" in col:
                print(f"  {col:<25} : €{val:,.2f}")
            else:
                print(f"  {col:<25} : {val}")
        print("="*60 + "\n")