"""Common types used throughout the XBID hybrid trading system.

This module defines a small collection of enums and data classes that capture
the fundamental entities in the market simulation such as orders and trades.
All classes here are intentionally lightweight and contain no behavioural
logic.  They exist solely to make the type contracts between different
components explicit and to centralise shared definitions.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class OrderSide(Enum):
    """Enumerates the two possible directions of a trade."""

    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    """Specifies whether an order is a limit order, market order or a cancellation."""

    LIMIT = "limit"
    MARKET = "market"
    CANCEL = "cancel"


@dataclass
class Order:
    """Represents a request to transact energy for a specific product.

    Parameters
    ----------
    id:
        Unique identifier of the order within the market engine.  Assigned
        automatically when the order is created.
    product_id:
        Identifier of the quarter‑hour delivery product for which this order is
        submitted.  Values range from ``0`` to ``num_products - 1``.
    side:
        Direction of the order (buy or sell).
    order_type:
        The order type: ``OrderType.LIMIT`` for a limit order specifying a
        price, ``OrderType.MARKET`` for a market order that executes against
        the best available prices, or ``OrderType.CANCEL`` for a cancellation
        request referencing an existing order via ``original_order_id``.
    price:
        Limit price of the order in €/MWh.  For market orders this value should
        be ``None``.  For cancellations the price is ignored.
    quantity:
        Quantity in MW.  Positive values indicate the volume to buy or sell.  A
        cancellation order should set quantity to zero.
    timestamp:
        Event time when the order was submitted (in minutes since the start of
        the trading day).  This is used for time priority when matching orders
        at the same price level.
    trader_id:
        Identifier of the participant that created the order.  Background
        participants and the RL agent may use different prefixes.
    original_order_id:
        When ``order_type`` is ``CANCEL``, this field identifies the order to
        cancel.  Otherwise it should be ``None``.
    """

    id: int
    product_id: int
    side: OrderSide
    order_type: OrderType
    price: Optional[float]
    quantity: float
    timestamp: float
    trader_id: str
    original_order_id: Optional[int] = None

    def is_active(self) -> bool:
        """Return whether this order represents an active resting order.

        Market orders and cancellation requests are never considered active,
        regardless of their remaining quantity.
        """
        return self.order_type == OrderType.LIMIT and self.quantity > 0


@dataclass
class Trade:
    """Captures the result of matching a buy and a sell order.

    Parameters
    ----------
    trade_id:
        Unique identifier for the trade generated by the matching engine.
    product_id:
        Identifier of the product in which the trade occurred.
    price:
        Transaction price in €/MWh determined by the resting order that was
        consumed.
    quantity:
        Executed quantity in MW.
    buy_order_id:
        Identifier of the buy order involved in the trade.
    sell_order_id:
        Identifier of the sell order involved in the trade.
    timestamp:
        Event time when the trade occurred (in minutes since the start of the
        trading day).
    """

    trade_id: int
    product_id: int
    price: float
    quantity: float
    buy_order_id: int
    sell_order_id: int
    timestamp: float